### ISSUE TITLE
프로젝트 설정

### ISSUE THREAD

**Issue by jhye90** [jhye90/GitHub-Repo#1]
## Description
프로젝트 설정

## Task
- [x] 프로젝트 생성
- [x] 패키지 구성 (presentation - domain - data - utils- di) 
- [x] 라이브러리 추가 (hilt, retrofit, lifecycle, databinding)
- [x] base 클래스 추가  

## Etc
,,
