### ISSUE TITLE
GitHub 리포지토리 검색 화면 presentation layer 구성

### ISSUE THREAD

**Issue by jhye90** [jhye90/GitHub-Repo#6]
## Description
GitHub 리포지토리 검색 화면 presentation layer 구성

## Task
- [x] 리파지토리 리스트 출력 
- [x] 검색하기
- [x] 스크롤하기
- [x] 재시도하기 (네트워크 에러)
- [x] 프로그래스바 출력
- [x] 리파지토리 결과 없을 경우 표시 

## Etc
,,
